# -*- coding: utf-8 -*-
"""01_Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uekYlgZgZYApoG7fQ6r_ygbBTEVGjyhG
"""

### Variables ###
my_string_variable = "My String Variable"
print(my_string_variable)


my_int_variable = 5
print(my_int_variable)


my_int_to_str_variable = str(my_int_variable)
print(my_int_to_str_variable)
print(type(my_int_to_str_variable))


my_bool_variable = False
print(my_bool_variable)