# -*- coding: utf-8 -*-
"""PrimerprogramaPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oqyv0AY-mxLokHPDPb52GOdCCleO6ifk
"""

#Este símbolo se utiliza para comentar el código.
print("hola grupo 230 de la carrera técnica de PROGRAMACIÓN")
#como consultar el tipo de dato
print(type("soy un dato str")) # tipo 'str'
print(type(5)) # tipo 'int'
print(type(1.5)) # tipo 'float'
print(type(3+1j)) # tipo 'complex'
print(type(True)) # tipo 'bool'
print(type(print('Mi cadena de texto'))) # tipo 'NoneType'